#spring:
#  application:
#    name: notification-service
#  profiles:
#    active: ${SPRING_PROFILES_ACTIVE:develop}
#  config:
#    import: ${CONFIG_IMPORT}
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        session:
          events:
            post_init: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${postgres_username}
    password: ${postgres_password}
    url: ${postgres_url}
  kafka:
    bootstrap-servers: 10.1.5.186:9092
    #  rabbitmq:
#    host: ${rabbit_host}
#    port: ${rabbit_port}
#    username: ${rabbit_username}
#    password: ${rabbit_password}
#    queue:
#      # noinspection SpringBootApplicationYaml
#      name: notification-queue
  application:
    name: product-service
server:
  port: 8086

logging:
  level:
    com.product.service: TRACE
  pattern:
    console: "%d{ISO8601} %highlight(%-5level{TRACE=blue, DEBUG=yellow}) [%green(%t)] %cyan(%C{1.}): %msg%n%throwable"
