apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: default
  labels:
    app: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 1

  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: localhost:5000/order-service
          env:
            - name: username
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: postgres-user
            - name: password
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: postgres-password
            - name: postgres_url
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_url
          ports:
            - containerPort: 8085
      restartPolicy: Always
