apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: default
  labels:
    app: eureka-server
spec:
  selector:
    matchLabels:
      app: eureka-server
  replicas: 1

  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: localhost:5000/eureka-server
          ports:
            - containerPort: 8761
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server-svc
  namespace: default
spec:
  selector:
    app: eureka-server
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
