apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka
  name: kafka-headless
spec:
  selector:
    app: kafka
  ports:
    - name: internal
      port: 9092
      targetPort: 9092
  type: ClusterIP