apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: default
  labels:
    app: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1

  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: localhost:5000/user-service
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
          env:
            - name: username
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: postgres-user
            - name: password
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: postgres-password
            - name: postgres_url
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_url
            - name: product_service_url
              valueFrom:
                configMapKeyRef:
                  name: module-url
                  key: product-service
          ports:
            - containerPort: 8081
      restartPolicy: Always
