apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: default
  labels:
    app: product-service
spec:
  selector:
    matchLabels:
      app: product-service
  replicas: 1

  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: localhost:5000/product-service
          env:
            - name: username
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: mongo-user
            - name: password
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: mongo-password
            - name: mongo_url
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: mongo_url
          ports:
            - containerPort: 8082
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: product-service-svc
  namespace: default
spec:
  selector:
    app: product-service
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082



