apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-job
spec:
  schedule: "0 0 * * *"  # Schedule the backup job to run daily at midnight (adjust as needed)
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup-container
              image: localhost:5000/backup-script
              command: ["/bin/bash", "/backup.sh"]
              env:
                - name: POSTGRES_HOST
                  value: "postgres-svc"
                - name: POSTGRES_PORT
                  value: "5432"
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: postgres-config-secret
                      key: postgres_db
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-config-secret
                      key: postgres_user
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-config-secret
                      key: postgres_password
              volumeMounts:
                - name: backup-volume
                  mountPath: /backup
          volumes:
            - name: backup-volume
              persistentVolumeClaim:
                claimName: backup-pvc
