apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
spec:
  resources:
    requests:
      storage: 60Gi
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: backup-pv
