apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: default
  labels:
    app: product-service
spec:
  selector:
    matchLabels:
      app: product-service
  replicas: 1

  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: eu.gcr.io/cheesecake-core/product-service
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
          env:
            - name: username
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: postgres-user
            - name: password
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: postgres-password
            - name: postgres_url
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_url
          ports:
            - containerPort: 8082
      restartPolicy: Always