apiVersion: v1
kind: Service
metadata:
  name: authentication-svc
  namespace: default
spec:
  selector:
    app: authentication-service
  type: NodePort
  ports:
    - port: 8086
      targetPort: 8086
