apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoDB
  namespace: default
  labels:
    app: mongoDB
spec:
  selector:
    matchLabels:
      app: mongoDB
  replicas: 1

  template:
    metadata:
      labels:
        app: mongoDB
    spec:
      containers:
        - name: mongoDB
          image: mongoDB:latest
          env:
            - name: mongoDB_PASSWORD
              value: mongoDB
          ports:
            - containerPort:
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: mongoDB-svc
  namespace: default
spec:
  selector:
    app: mongoDB
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
