apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1

  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: default
spec:
  selector:
    app: postgres
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
