apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
  namespace: default
  labels:
    app: email-service
spec:
  selector:
    matchLabels:
      app: email-service
  replicas: 1
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - name: email-service
          image: localhost:5000/email-service
          resources:
            limits:
              cpu: 400m
              memory: 500Mi
          ports:
            - containerPort: 8087
      restartPolicy: Always
