apiVersion: v1
kind: Service
metadata:
  name: notification-service-svc
  namespace: default
spec:
  selector:
    app: notification-service
  type: NodePort
  ports:
    - port: 8086
      targetPort: 8086


