eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-svc:8761/eureka/
spring:
  data:
    mongodb:
      host: mongo-svc
      port: 27017
      username: ${username}
      password: ${password}
      uri: ${mongo_uri}
      database: product-db
      authentication-database: admin
  application:
    name: product-service
server:
  port: 8082
file:
  receiver:
    url: ${file_receiver_url}

logging:
  level:
    com.product.service: TRACE
  pattern:
    console: "%d{ISO8601} %highlight(%-5level{TRACE=blue, DEBUG=yellow}) [%green(%t)] %cyan(%C{1.}): %msg%n%throwable"
