apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgres_url:
    "jdbc:postgresql://34.65.51.249:5432/cheesecake_db"
#    "jdbc:postgresql://postgres-svc:5432/cheesecake_db"
