apiVersion: v1
kind: Secret
metadata:
  name: postgres-config-secret
data:
  postgres_db: Y2hlZXNlY2FrZV9kYg== # cheesecake_db
  postgres_user: YWRtaW4= # admin
  postgres_password: cGFzc3dvcmQ= # password
