apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: default
  labels:
    app: notification-service
spec:
  selector:
    matchLabels:
      app: notification-service
  replicas: 1

  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: localhost:5000/notification-service
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
          env:
#                 RABBITMQ
            - name: rabbit_username
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: username
            - name: rabbit_password
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: password
            - name: rabbit_host
              valueFrom:
                configMapKeyRef:
                  name: rabbit-config
                  key: rabbit_host
            - name: rabbit_port
              valueFrom:
                configMapKeyRef:
                  name: rabbit-config
                  key: rabbit_port
#                 POSTGRES
            - name: postgres_username
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: postgres-user
            - name: postgres_password
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: postgres-password
            - name: postgres_url
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_url
          ports:
            - containerPort: 8086
      restartPolicy: Always