eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-svc:8761/eureka/
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  datasource:
    username: ${username}
    password: ${password}
    url: ${postgres_url}
  application:
    name: authentication-server
server:
  port: 8085
