server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
spring:
  application:
    name: config-server
  security:
    user:
      name: root
      password: root
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI}
          password: ${CONFIG_GIT_PASSWORD}
          username: ${CONFIG_GIT_USERNAME}
          default-label: ${CONFIG_GIT_DEFAULT_LABEL}
          clone-on-start: true
          search-paths: { application }
