server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
spring:
  application:
    name: config-server
  security:
    user:
      name: root
      password: root
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: ${GIT_DEFAULT_LABEL}
          clone-on-start: true
          search-paths: { application }

logging:
  level:
    com.product.service: TRACE
  pattern:
    console: "%d{ISO8601} %highlight(%-5level{TRACE=blue, DEBUG=yellow}) [%green(%t)] %cyan(%C{1.}): %msg%n%throwable"
