apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  mongo_uri:
#    "mongodb://root:root@mongo-svc:27017/product-db"
    "mongodb://root:root@mongo-svc:27017/product-db?authSource=admin&retryWrites=true&w=majority"
